import { Inter, Josefin_Sans } from 'next/font/google'
import Image from 'next/image'
import './globals.css'
import recordsImg from '../../public/assets/archive.jpg'
import homeImg from '../../public/images/main.png'

const inter = Inter({ subsets: ['latin'] })
const josefin = Josefin_Sans({ weight: "300", subsets: ['latin'] })

export const metadata = {
  title: 'Records Room Inventory',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&display=swap" rel="stylesheet" /> 
      </head>
      <body className={`mt-7 ${josefin.className}`}>
        <div className='mx-auto relative w-fit px-8 py-2 text-center outline outline-2 outline-gray-400'>
          <h1 className='text-center text-3xl text-gray-100 drop-shadow-lg'>Records Room Inventory</h1>
        </div>
        {/* <Image src={homeImg} alt="records" className='records-img absolute mx-auto' /> */}
        {/* <Image src={recordsImg} alt="records" className='records-img mx-auto blur-sm' /> */}
        
        {children}
      </body>
    </html>
  )
}
